name: Policy check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install profanity-check
    - name: Lint with profanity-check
      run: |
        # Every file in the repo that is treated as text
        FILES2CHECK=$(git ls-files | xargs git grep --name-only -I -e . --)

        python3.7 -W ignore ./scripts/policycheck.py 0.5 $FILES2CHECK
